// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnM9VmgX667eQ2zEVrY7Vp6n6V8_HmDXA',
    appId: '1:226424252906:web:02afbd414b370cf320aa93',
    messagingSenderId: '226424252906',
    projectId: 'repaso2eva',
    authDomain: 'repaso2eva.firebaseapp.com',
    storageBucket: 'repaso2eva.firebasestorage.app',
    measurementId: 'G-SX8040ZB0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3hPsfSPC0eE7CMk0yZoYIj87uiNAZz4',
    appId: '1:964521149019:android:90ae9064771d42a705357e',
    messagingSenderId: '964521149019',
    projectId: 'repaso2evaluacion',
    storageBucket: 'repaso2evaluacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7nqEW3m3xLLVq4A2f80HZ0QPr-I6mEg',
    appId: '1:964521149019:ios:367acf4f45f80e9505357e',
    messagingSenderId: '964521149019',
    projectId: 'repaso2evaluacion',
    storageBucket: 'repaso2evaluacion.firebasestorage.app',
    iosBundleId: 'com.example.repaso2eva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpVwM9K4Sl_0GnMjmzniRFj4y6cGoUVjI',
    appId: '1:226424252906:ios:d0dc26da3f8e88b020aa93',
    messagingSenderId: '226424252906',
    projectId: 'repaso2eva',
    storageBucket: 'repaso2eva.firebasestorage.app',
    iosBundleId: 'com.example.repaso2eva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnM9VmgX667eQ2zEVrY7Vp6n6V8_HmDXA',
    appId: '1:226424252906:web:d1d53e2739c3f71020aa93',
    messagingSenderId: '226424252906',
    projectId: 'repaso2eva',
    authDomain: 'repaso2eva.firebaseapp.com',
    storageBucket: 'repaso2eva.firebasestorage.app',
    measurementId: 'G-MBFVW83B55',
  );
}